# http://www.appveyor.com/docs/appveyor-yml
# http://www.appveyor.com/docs/lang/nodejs-iojs

branches:
  # whitelist
  only:
    - master

environment:
  matrix:
    # node.js
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"

install:
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - node_modules\.bin\lab test\index.js -cv

build: off

# build version format
version: "{build}"
